name: fairseq-image-captioning
channels:
  - pytorch
dependencies:
  - python=3.6
  - pytorch=1.3
  - cudatoolkit=10.1
  - torchvision=0.4
  - scipy=1.3.1
  - tqdm=4.36
  - pip
  - pip:
      - fairseq==0.8.0
      - sacremoses==0.0.35
      - subword-nmt==0.3.6
